openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: This Documentaton is done my asd
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.13

servers:
  - url: http://localhost:4000/
    description: This is local Server

paths:
  /api/name1:
    get:
      summary: Thi is first
      description:  Our first Api
      responses:
        '200':
          description: Success
        '400':
          description: Not found
        500:
          description: Server Error
 

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string